### Get all items
GET http://localhost:3333/users

### Create a new item
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Sample Item",
  "description": "This is a test item."
}

### Update an item
PUT http://localhost:3333/users/c9dbf386-b28c-4f7e-aadf-1930bee4d284
Content-Type: application/json

{
  "name": "Updated Item",
  "description": "This item has been updated."
}

#### Delete an item
DELETE http://localhost:3333/users/7a037236-9408-4674-8393-3e49554389bc

